name: Ruby on Rails CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      PSQL_DB_HOST: ${{ secrets.PSQL_DB_HOST }}
      PSQL_DATABASE: ${{ secrets.PSQL_DATABASE }}
      PSQL_USER: ${{ secrets.PSQL_USER }}
      PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.PSQL_DATABASE }}  
          POSTGRES_USER: ${{ secrets.PSQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PSQL_PASSWORD || 'default_pass' }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=10

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "PSQL_DATABASE=${{ secrets.PSQL_DATABASE }}"
          echo "PSQL_USER=${{ secrets.PSQL_USER }}"
          echo "PSQL_PASSWORD=${{ secrets.PSQL_PASSWORD }}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Set up bundler
        run: |
          gem install bundler
          bundle install

      - name: Set up database configuration
        run: |
          cat > config/database.yml <<EOL
          development:
            adapter: postgresql
            encoding: unicode
            pool: 5
            host: postgres
            username: ${PSQL_USER}
            password: ${PSQL_PASSWORD}
            database: ${PSQL_DATABASE}
          EOL

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -U ${PSQL_USER} && break
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Set up the database
        run: |
          bundle exec rake db:create db:migrate

      - name: Run tests with RSpec
        run: |
          bundle exec rspec
          
      - name: Run Rubocop
        run: |
          bundle exec rubocop
