name: Ruby on Rails CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.PSQL_DATABASE }}  
          POSTGRES_USER: ${{ secrets.PSQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U $POSTGRES_USER" --health-timeout=30s --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Set up bundler
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        run: |
          # Dynamically generate the database.yml file
          echo "development:" > config/database.yml
          echo "  adapter: postgresql" >> config/database.yml
          echo "  encoding: unicode" >> config/database.yml
          echo "  pool: 5" >> config/database.yml
          echo "  host: postgres" >> config/database.yml
          echo "  username: ${PSQL_USER}" >> config/database.yml
          echo "  password: ${PSQL_PASSWORD}" >> config/database.yml
          echo "  database: ${PSQL_DATABASE}" >> config/database.yml

      - name: Install dependencies
        run: |
          bundle install

      - name: Set up the database
        run: |
          bundle exec rake db:create db:migrate

      - name: Run tests with RSpec
        run: |
          bundle exec rspec
          
      - name: Run Rubocop
        run: |
          bundle exec rubocop
